name = "Gearheaven 齿轮星都"
author = "Unda Rubra"
version = "alpha3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "897dc2d2e4d2b60fc6a9a47a0579c89b112e099e2010965eb6f1ab91d5f85cee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
