name = "Gearheaven 齿轮星都"
author = "Unda Rubra"
version = "alpha3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "234308e0a847659a03dd7fdeb0616043ffa686ac34552f9a1b08de885b4501d5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
