name = "Gearheaven 齿轮星都"
author = "Unda Rubra"
version = "alpha3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3c9811bbc28affd6d6ceda9d46c0ffadca7bab595956435731fcfab0e504a93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
